const planeData = {
    b737: {
        name: "Boeing 737",
        image: "imgs/planes/b737.webp",
        parts: [
            { name: "Fuselage", description: "Main body of the aircraft, carrying passengers, cargo and systems. Manufactured primarily by Boeing, with major structural components supplied by Boeing partners." },
            { name: "Cockpit", description: "Houses the pilots and flight controls. Manufactured and integrated by Boeing using avionics from suppliers such as Honeywell and Collins Aerospace." },
            { name: "Wings", description: "Generate lift, contain fuel and support the engines. Manufactured primarily by Boeing." },
            { name: "Horizontal stabilizer", description: "Provides pitch stability and supports the elevators. Manufactured by Boeing and aerospace suppliers." },
            { name: "Vertical stabilizer / fin", description: "Provides directional stability and supports the rudder. Manufactured by Boeing and suppliers." },
            { name: "Rudder", description: "Controls yaw, moving the aircraft's nose left or right. Manufactured by Boeing and suppliers." },
            { name: "Elevators", description: "Control pitch, moving the nose up or down. Manufactured by Boeing and suppliers." },
            { name: "Ailerons", description: "Control the aircraft's roll. Manufactured by Boeing and suppliers." },
            { name: "Flaps", description: "Increase wing lift during takeoff and landing. Manufactured by Boeing and aerospace subcontractors." },
            { name: "Leading-edge slats", description: "Increase lift at low speeds. Manufactured by Boeing and suppliers." },
            { name: "Spoilers", description: "Reduce lift and help control roll and slow the aircraft after landing. Manufactured by Boeing and suppliers." },
            { name: "CFM56 engines", description: "Produce thrust on most 737 Classic and Next Generation aircraft. Manufactured by CFM International, a GE Aerospace/Safran joint venture." },
            { name: "CFM56-3 engines", description: "Produce thrust on 737 Classic aircraft. Manufactured by CFM International." },
            { name: "CFM56-7B engines", description: "Produce thrust on 737 Next Generation aircraft. Manufactured by CFM International." },
            { name: "LEAP-1B engines", description: "Produce thrust on the 737 MAX. Manufactured by CFM International." },
            { name: "JT8D engines", description: "Produce thrust on early 737 Original aircraft. Manufactured by Pratt & Whitney." },
            { name: "Engine nacelles", description: "Enclose and streamline the engines. Manufactured by Boeing and specialist suppliers including Safran Nacelles." },
            { name: "Engine pylons", description: "Attach the engines to the wings and transfer engine loads into the aircraft structure. Manufactured by Boeing and suppliers." },
            { name: "Landing gear", description: "Supports the aircraft on the ground and absorbs landing forces. Manufactured by Boeing and specialist landing-gear suppliers including Safran Landing Systems." },
            { name: "Wheels and brakes", description: "Allow taxiing and provide braking during landing. Supplied by companies including Safran Landing Systems and Collins Aerospace." },
            { name: "Fuel system", description: "Stores fuel in the wings and delivers it to the engines. Supplied by Boeing and specialist fuel-system manufacturers." },
            { name: "Hydraulic system", description: "Provides power for flight controls, landing gear and brakes. Supplied by Boeing and specialist hydraulic-system manufacturers." },
            { name: "Electrical system", description: "Generates and distributes electrical power throughout the aircraft. Supplied by Boeing and specialist electrical-system manufacturers." },
            { name: "APU", description: "Provides electrical power and compressed air when the main engines aren't running. Manufactured by Honeywell and other suppliers depending on the 737 generation." },
            { name: "Air-conditioning system", description: "Controls cabin temperature and circulates conditioned air. Major components supplied by Boeing and companies including Collins Aerospace." },
            { name: "Pressurization system", description: "Maintains safe cabin pressure at cruising altitude. Supplied by Boeing and specialist environmental-control manufacturers." },
            { name: "Flight-management computer", description: "Calculates routes, navigation information and aircraft-performance data. Major avionics supplied by Honeywell and Collins Aerospace." },
            { name: "Air-data computers", description: "Calculate airspeed, altitude and other flight information. Supplied by Honeywell and other avionics manufacturers." },
            { name: "Inertial reference system", description: "Provides aircraft position, attitude and movement information. Supplied by Honeywell and Collins Aerospace." },
            { name: "Flight-control computers", description: "Process pilot inputs and control the aircraft's flight-control systems. Developed/integrated by Boeing with systems from specialist avionics suppliers." },
            { name: "Autopilot", description: "Automatically controls the aircraft's flight path when engaged. Supplied by Boeing and avionics manufacturers including Collins Aerospace and Honeywell." },
            { name: "Flight displays", description: "Show pilots speed, altitude, heading, navigation and aircraft-system information. Supplied by Boeing and avionics manufacturers including Collins and Honeywell." },
            { name: "Communication radios", description: "Allow pilots to communicate with ATC and other aircraft. Supplied by Collins Aerospace, Honeywell and other manufacturers." },
            { name: "Navigation equipment", description: "Determines aircraft position and assists with navigation. Supplied by Honeywell, Collins Aerospace and other manufacturers." },
            { name: "Passenger doors", description: "Provide access to and from the passenger cabin. Manufactured by Boeing and aerospace suppliers." },
            { name: "Cargo doors", description: "Provide access to the forward and aft cargo compartments. Manufactured by Boeing and suppliers." },
            { name: "Cargo handling system", description: "Moves and secures baggage and cargo inside the aircraft. Supplied by Boeing and specialist cargo-system manufacturers." },
            { name: "Cabin windows", description: "Provide outside visibility while maintaining cabin pressure. Manufactured by specialist aerospace window suppliers." },
            { name: "Passenger seats", description: "Provide seating and restraint systems. Supplied by manufacturers such as Recaro, Safran Seats and Collins Aerospace, depending on airline." },
            { name: "Overhead bins", description: "Store passengers' carry-on luggage. Manufactured/supplied by Boeing and cabin-interior suppliers." },
            { name: "Galleys", description: "Provide facilities for preparing and storing food and drinks. Supplied by Boeing and specialist cabin suppliers." },
            { name: "Lavatories", description: "Provide toilet and washing facilities. Supplied by Boeing and specialist cabin-interior manufacturers." },
            { name: "Cabin lighting", description: "Provides general, reading and emergency lighting. Supplied by Boeing and specialist lighting manufacturers." },
            { name: "Passenger entertainment system", description: "Provides movies, music, information and other entertainment. Supplied by companies such as Panasonic Avionics, Thales and Collins Aerospace, depending on aircraft." },
        ]
    },
    b747: {
        name: "Boeing 747",
        image: "imgs/planes/b747.webp",
        parts: [
            { name: "Fuselage", description: "Main body of the aircraft, carrying passengers, cargo and systems. Manufactured primarily by Boeing, with structural components supplied by Boeing subcontractors." },
            { name: "Upper deck", description: "Raised forward section that gives the 747 its distinctive hump and provides additional passenger/cockpit space. Manufactured by Boeing." },
            { name: "Wings", description: "Generate lift, contain fuel and support the four engines. Manufactured primarily by Boeing." },
            { name: "Horizontal stabilizer", description: "Provides pitch stability and supports the elevators. Manufactured by Boeing and aerospace suppliers." },
            { name: "Vertical stabilizer / fin", description: "Provides directional stability and supports the rudder. Manufactured by Boeing and suppliers." },
            { name: "Rudder", description: "Controls yaw, moving the aircraft's nose left or right. Manufactured by Boeing and suppliers." },
            { name: "Elevators", description: "Control pitch, moving the aircraft's nose up or down. Manufactured by Boeing and suppliers." },
            { name: "Ailerons", description: "Control the aircraft's roll. Manufactured by Boeing and suppliers." },
            { name: "Flaps", description: "Increase wing lift during takeoff and landing. Manufactured by Boeing and aerospace subcontractors." },
            { name: "Leading-edge devices", description: "Increase lift at lower speeds during takeoff and landing. Manufactured by Boeing and suppliers." },
            { name: "Spoilers", description: "Reduce lift and help control roll and slow the aircraft after landing. Manufactured by Boeing and suppliers." },
            { name: "Engines — JT9D", description: "Produce thrust on many early 747 variants. Manufactured by Pratt & Whitney." },
            { name: "Engines — CF6", description: "Produce thrust on many 747 variants. Manufactured by General Electric." },
            { name: "Engines — RB211", description: "Produce thrust on many 747 variants. Manufactured by Rolls-Royce." },
            { name: "Engines — GEnx-2B", description: "Produce thrust on the 747-8. Manufactured by GE Aerospace." },
            { name: "Engine nacelles", description: "Enclose and streamline the engines. Manufactured by Boeing and specialist suppliers." },
            { name: "Engine pylons", description: "Attach the four engines to the wings and transfer engine loads into the wing structure. Manufactured by Boeing and suppliers." },
            { name: "Landing gear", description: "Supports the aircraft on the ground and absorbs landing forces. Manufactured by Boeing and specialist landing-gear suppliers including Menasco and later Safran Landing Systems." },
            { name: "Wheels and brakes", description: "Allow taxiing and provide braking during landing. Supplied by specialist manufacturers including Goodrich and Safran Landing Systems." },
            { name: "Fuel system", description: "Stores fuel primarily inside the wings and delivers it to the engines. Supplied by Boeing and specialist fuel-system manufacturers." },
            { name: "Hydraulic system", description: "Provides power for flight controls, landing gear, brakes and other systems. Supplied by Boeing and specialist hydraulic-system manufacturers." },
            { name: "Electrical system", description: "Generates and distributes electrical power throughout the aircraft. Supplied by Boeing and specialist electrical-system manufacturers." },
            { name: "APU", description: "Provides electrical power and compressed air when the main engines aren't running. Manufactured by companies including AlliedSignal/Honeywell, depending on variant." },
            { name: "Air-conditioning system", description: "Controls cabin temperature and supplies conditioned air. Supplied by Boeing and specialist environmental-control manufacturers." },
            { name: "Pressurization system", description: "Maintains safe cabin pressure at cruising altitude. Supplied by Boeing and specialist system manufacturers." },
            { name: "Flight-management computers", description: "Calculate routes, navigation information and aircraft-performance data. Supplied by Boeing and avionics manufacturers including Honeywell." },
            { name: "Air-data computers", description: "Calculate airspeed, altitude and other flight information. Supplied by Honeywell and other avionics manufacturers." },
            { name: "Inertial navigation system", description: "Provides aircraft position, heading and movement information. Supplied by manufacturers including Honeywell and Collins." },
            { name: "Autopilot system", description: "Automatically controls the aircraft's flight path when engaged. Supplied by Boeing and avionics manufacturers including Honeywell and Collins." },
            { name: "Flight displays", description: "Show pilots speed, altitude, heading, navigation and aircraft-system information. Supplied by Boeing and avionics manufacturers." },
            { name: "Communication radios", description: "Allow pilots to communicate with ATC and other aircraft. Supplied by manufacturers including Collins and Honeywell." },
            { name: "Navigation equipment", description: "Determines aircraft position and assists with navigation. Supplied by Honeywell, Collins and other avionics manufacturers." },
            { name: "Passenger doors", description: "Provide access to and from the passenger cabin. Manufactured by Boeing and aerospace suppliers." },
            { name: "Cargo doors", description: "Provide access to the aircraft's cargo compartments. Manufactured by Boeing and suppliers." },
            { name: "Nose cargo door", description: "Allows large cargo to be loaded through the front of applicable 747 freighter versions. Manufactured by Boeing." },
            { name: "Cargo handling system", description: "Moves and secures pallets and containers inside the aircraft. Supplied by Boeing and specialist cargo-system manufacturers." },
            { name: "Cabin windows", description: "Provide outside visibility while maintaining cabin pressure. Manufactured by specialist aerospace window suppliers." },
            { name: "Passenger seats", description: "Provide passenger seating and restraint systems. Supplied by manufacturers such as Recaro, Safran Seats and others, depending on airline." },
            { name: "Overhead bins", description: "Store passengers' carry-on luggage. Manufactured or supplied by Boeing and cabin-interior suppliers." },
            { name: "Galleys", description: "Provide facilities for preparing and storing food and drinks. Supplied by Boeing and specialist cabin suppliers." },
            { name: "Lavatories", description: "Provide toilet and washing facilities. Supplied by Boeing and specialist cabin-interior manufacturers." },
            { name: "Cabin lighting", description: "Provides general, reading and emergency lighting. Supplied by Boeing and specialist lighting manufacturers." },
            { name: "Passenger entertainment system", description: "Provides movies, music, information and other entertainment. Supplied by various companies depending on airline and 747 variant." },
        ]
    },
    b757: {
        name: "Boeing 757",
        image: "imgs/planes/b757.webp",
        parts: [
            { name: "Fuselage", description: "Main body of the aircraft, carrying passengers, cargo and systems. Manufactured primarily by Boeing and Rockwell International." },
            { name: "Wings", description: "Generate lift and contain fuel tanks. Manufactured by Boeing with major components from suppliers including Hawker de Havilland and Heath Tecna." },
            { name: "Horizontal stabilizer", description: "Keeps the aircraft stable in pitch and supports the elevators. Manufactured by Boeing and suppliers including LTV and Northrop Grumman." },
            { name: "Vertical stabilizer / fin", description: "Keeps the aircraft stable directionally and supports the rudder. Manufactured by Boeing and suppliers including Vought." },
            { name: "Rudder", description: "Controls yaw, moving the aircraft's nose left or right. Manufactured by Boeing and its structural subcontractors." },
            { name: "Elevators", description: "Control the aircraft's pitch, moving the nose up or down. Manufactured by Boeing and its subcontractors." },
            { name: "Ailerons", description: "Control the aircraft's roll by moving the wings up or down. Manufactured by Boeing and its subcontractors." },
            { name: "Flaps", description: "Extend from the wings to increase lift during takeoff and landing. Major components manufactured by suppliers including Grumman, Shorts and CASA." },
            { name: "Leading-edge slats", description: "Extend from the front of the wings to increase lift at low speeds. Manufactured by Boeing and suppliers including Fairchild." },
            { name: "Spoilers", description: "Reduce lift and assist with roll control and landing braking. Manufactured by Boeing and suppliers including Alenia." },
            { name: "Engines — PW2000", description: "Produce thrust for the aircraft. Manufactured by Pratt & Whitney." },
            { name: "Engines — RB211-535", description: "Alternative engine family producing thrust for the 757. Manufactured by Rolls-Royce." },
            { name: "Engine nacelles", description: "Enclose and streamline the engines. Manufactured by Boeing and suppliers including Rohr." },
            { name: "Engine pylons", description: "Attach the engines to the wings and transfer engine loads into the wing structure. Manufactured by Boeing and suppliers." },
            { name: "Landing gear", description: "Supports the aircraft on the ground and absorbs landing forces. Manufactured primarily by Menasco." },
            { name: "Wheels and brakes", description: "Allow the aircraft to taxi and provide braking during landing. Supplied by manufacturers including Goodrich and Honeywell." },
            { name: "Fuel system", description: "Stores fuel in the wings and delivers it to the engines. Major components supplied by companies including Goodrich and Lucas Aerospace." },
            { name: "Hydraulic system", description: "Provides high-pressure power for flight controls, landing gear and brakes. Components supplied by manufacturers including Honeywell, Vickers and Parker Aerospace." },
            { name: "Electrical system", description: "Generates and distributes electricity throughout the aircraft. Components supplied by Boeing and specialist suppliers including Parker Aerospace." },
            { name: "APU", description: "Small turbine engine that supplies electrical power and compressed air while the main engines aren't operating. Manufactured by Honeywell." },
            { name: "Air-conditioning system", description: "Controls cabin temperature and supplies conditioned air. Major components supplied by Honeywell and Parker Aerospace." },
            { name: "Pressurization system", description: "Maintains safe cabin pressure at high altitude. Systems and components supplied by Boeing and specialist suppliers including Honeywell." },
            { name: "Flight-management computer", description: "Helps calculate navigation, routes and aircraft performance. Manufactured primarily by Honeywell." },
            { name: "Air-data computers", description: "Process pressure measurements to determine airspeed, altitude and other flight data. Manufactured by Honeywell and other avionics suppliers." },
            { name: "Inertial reference system", description: "Provides aircraft attitude, motion and navigation information. Major equipment supplied by Honeywell." },
            { name: "Autopilot system", description: "Automatically controls the aircraft's flight path when engaged. Avionics supplied by companies including Collins and Honeywell." },
            { name: "Flight displays", description: "Show pilots information such as speed, altitude, heading and navigation. Supplied by Boeing and avionics manufacturers including Collins and Honeywell." },
            { name: "Communication radios", description: "Allow pilots to communicate with air traffic control and other aircraft. Supplied by avionics manufacturers including Collins and Honeywell." },
            { name: "Navigation equipment", description: "Helps determine aircraft position and navigation information. Supplied by manufacturers including Honeywell and Collins." },
            { name: "Passenger doors", description: "Provide access to and from the passenger cabin. Manufactured by Boeing and specialist structural suppliers." },
            { name: "Cargo doors", description: "Provide access to the aircraft's cargo compartments. Manufactured by Boeing and suppliers." },
            { name: "Cabin windows", description: "Provide passengers with outside visibility while maintaining cabin pressure. Manufactured by specialist aerospace window suppliers." },
            { name: "Passenger seats", description: "Provide seating and restraint systems for passengers. Supplied by various aircraft-seat manufacturers depending on the airline." },
            { name: "Overhead bins", description: "Store passenger carry-on baggage. Manufactured by Boeing and cabin-interior suppliers." },
            { name: "Galleys", description: "Provide facilities for preparing and storing food and drinks. Manufactured or supplied by Boeing and specialist cabin-interior companies." },
            { name: "Lavatories", description: "Provide toilet and washing facilities onboard. Manufactured or supplied by Boeing and specialist cabin suppliers." },
        ]
    },
    b767: {
        name: "Boeing 767",
        image: "imgs/planes/b767.webp",
        parts: [
            { name: "Fuselage", description: "Main body of the aircraft, carrying passengers, cargo, fuel-related systems and equipment. Manufactured primarily by Boeing, with major structural work from suppliers including Aeritalia and CTDC." },
            { name: "Wings", description: "Generate lift and contain fuel tanks. Manufactured by Boeing, with components supplied by companies including Aeritalia and others." },
            { name: "Horizontal stabilizer", description: "Provides pitch stability and supports the elevators. Manufactured by Boeing and major structural suppliers." },
            { name: "Vertical stabilizer / fin", description: "Provides directional stability and supports the rudder. Manufactured by Boeing and structural suppliers." },
            { name: "Rudder", description: "Controls yaw, moving the aircraft's nose left or right. Manufactured by Boeing and suppliers." },
            { name: "Elevators", description: "Control pitch, moving the aircraft's nose up or down. Manufactured by Boeing and suppliers." },
            { name: "Ailerons", description: "Control the aircraft's roll. Manufactured by Boeing and suppliers." },
            { name: "Flaps", description: "Increase wing lift during takeoff and landing. Manufactured by Boeing with components from major aerospace suppliers." },
            { name: "Leading-edge slats", description: "Increase lift at low speeds. Manufactured by Boeing and aerospace subcontractors." },
            { name: "Spoilers", description: "Reduce lift and assist with roll control and braking after landing. Manufactured by Boeing and suppliers." },
            { name: "Engines — CF6-80A/80C2", description: "Produce thrust for the aircraft. Manufactured by General Electric." },
            { name: "Engines — PW4000", description: "Alternative engine family producing thrust. Manufactured by Pratt & Whitney." },
            { name: "Engines — RB211-524", description: "Alternative engine family used on some 767s. Manufactured by Rolls-Royce." },
            { name: "Engine nacelles", description: "Enclose and streamline the engines. Manufactured by Boeing and specialist suppliers including Rohr." },
            { name: "Engine pylons", description: "Attach the engines to the wings and transfer engine loads into the aircraft structure. Manufactured by Boeing and suppliers." },
            { name: "Landing gear", description: "Supports the aircraft on the ground and absorbs landing forces. Manufactured by Menasco and other aerospace suppliers." },
            { name: "Wheels and brakes", description: "Allow taxiing and provide braking during landing. Supplied by manufacturers including Goodrich and other specialist companies." },
            { name: "Fuel system", description: "Stores fuel mainly inside the wings and delivers it to the engines. Major components supplied by Boeing and specialist fuel-system manufacturers." },
            { name: "Hydraulic system", description: "Provides hydraulic power for flight controls, landing gear, brakes and other systems. Components supplied by companies including Vickers, Parker and Boeing." },
            { name: "Electrical system", description: "Generates and distributes electrical power throughout the aircraft. Supplied by Boeing and specialist electrical-system manufacturers." },
            { name: "APU", description: "Provides electrical power and compressed air when the main engines are shut down. Manufactured by AlliedSignal/Honeywell, depending on aircraft configuration." },
            { name: "Air-conditioning system", description: "Controls cabin temperature and circulates conditioned air. Major components supplied by companies including Honeywell and Liebherr." },
            { name: "Pressurization system", description: "Maintains safe cabin pressure at high altitude. Manufactured or supplied by Boeing and specialist system manufacturers." },
            { name: "Flight-management computer", description: "Calculates routes, navigation information and aircraft-performance data. Major avionics supplied by Honeywell." },
            { name: "Air-data computers", description: "Calculate airspeed, altitude and other flight information from air-pressure measurements. Supplied by Honeywell and other avionics manufacturers." },
            { name: "Inertial reference system", description: "Provides aircraft position, attitude and movement information. Supplied by Honeywell and other avionics manufacturers." },
            { name: "Autopilot / flight-control system", description: "Helps automatically control the aircraft's flight path. Major systems supplied by Honeywell and Collins." },
            { name: "Flight displays", description: "Display speed, altitude, heading, navigation and system information to pilots. Supplied by Boeing and avionics manufacturers including Collins and Honeywell." },
            { name: "Communication radios", description: "Allow communication with ATC and other aircraft. Supplied by avionics manufacturers including Collins and Honeywell." },
            { name: "Navigation equipment", description: "Determines aircraft position and assists navigation. Supplied by companies including Collins and Honeywell." },
            { name: "Passenger doors", description: "Allow passengers and crew to enter and leave the aircraft. Manufactured by Boeing and specialist aerospace suppliers." },
            { name: "Cargo doors", description: "Provide access to the large cargo compartments. Manufactured by Boeing and structural suppliers." },
            { name: "Cargo handling system", description: "Moves and secures cargo containers and pallets inside the aircraft. Supplied by Boeing and specialist cargo-system manufacturers." },
            { name: "Cabin windows", description: "Provide passenger visibility while maintaining cabin pressure. Manufactured by specialist aerospace window suppliers." },
            { name: "Passenger seats", description: "Provide seating and passenger restraint systems. Supplied by companies such as Recaro, Zodiac Aerospace/Safran and others, depending on airline." },
            { name: "Overhead bins", description: "Store passenger carry-on luggage. Manufactured or supplied by Boeing and cabin-interior companies." },
            { name: "Galleys", description: "Provide facilities for preparing and storing food and drinks. Supplied by Boeing and specialist cabin suppliers." },
            { name: "Lavatories", description: "Provide toilet and washing facilities. Supplied by Boeing and specialist cabin-interior manufacturers." },
        ]
    },
    b777: {
        name: "Boeing 777",
        image: "imgs/planes/b777.webp",
        parts: [
            { name: "Fuselage", description: "Main body of the aircraft, carrying passengers, cargo and major systems. Manufactured primarily by Boeing, with major sections/components supplied by Mitsubishi Heavy Industries, Kawasaki Heavy Industries and Fuji Heavy Industries." },
            { name: "Wings", description: "Generate lift, contain fuel and support the engines. Manufactured primarily by Boeing, with major components from Japanese partners including Mitsubishi Heavy Industries, Kawasaki Heavy Industries and Fuji Heavy Industries." },
            { name: "Horizontal stabilizer", description: "Provides pitch stability and supports the elevators. Manufactured by Boeing and Japanese aerospace partners." },
            { name: "Vertical stabilizer / fin", description: "Provides directional stability and supports the rudder. Manufactured by Boeing and aerospace partners." },
            { name: "Rudder", description: "Controls yaw, moving the aircraft's nose left or right. Manufactured by Boeing and suppliers." },
            { name: "Elevators", description: "Control pitch, moving the nose up or down. Manufactured by Boeing and suppliers." },
            { name: "Ailerons", description: "Control the aircraft's roll. Manufactured by Boeing and suppliers." },
            { name: "Flaps", description: "Increase wing lift during takeoff and landing. Manufactured by Boeing and aerospace partners." },
            { name: "Leading-edge slats", description: "Increase lift at low speeds. Manufactured by Boeing and suppliers." },
            { name: "Spoilers", description: "Reduce lift and help control roll and slow the aircraft after landing. Manufactured by Boeing and suppliers." },
            { name: "GE90 engines", description: "Produce thrust on many 777 variants. Manufactured by General Electric." },
            { name: "PW4000 engines", description: "Produce thrust on certain 777 variants. Manufactured by Pratt & Whitney." },
            { name: "Trent 800 engines", description: "Produce thrust on certain 777 variants. Manufactured by Rolls-Royce." },
            { name: "GE9X engines", description: "Produce thrust on the 777X family. Manufactured by General Electric Aerospace." },
            { name: "Engine nacelles", description: "Enclose and streamline the engines. Manufactured by Boeing and specialist suppliers including Safran Nacelles." },
            { name: "Engine pylons", description: "Attach the engines to the wings and transfer engine loads into the structure. Manufactured by Boeing and suppliers." },
            { name: "Landing gear", description: "Supports the aircraft on the ground and absorbs landing forces. Manufactured primarily by Safran Landing Systems and Boeing." },
            { name: "Wheels and brakes", description: "Allow taxiing and provide braking during landing. Supplied by companies including Safran Landing Systems and Collins Aerospace." },
            { name: "Fuel system", description: "Stores fuel in the wings and center tank and delivers it to the engines. Manufactured or supplied by Boeing and specialist fuel-system companies." },
            { name: "Hydraulic system", description: "Provides power for flight controls, landing gear, brakes and other systems. Major components supplied by Boeing and companies including Parker Aerospace and Safran." },
            { name: "Electrical system", description: "Generates and distributes electrical power throughout the aircraft. Supplied by Boeing and specialist electrical-system manufacturers." },
            { name: "APU", description: "Provides electricity and compressed air when the main engines aren't running. Manufactured by Honeywell." },
            { name: "Air-conditioning system", description: "Controls cabin temperature and supplies conditioned air. Major components supplied by Boeing and companies including Liebherr and Collins Aerospace." },
            { name: "Pressurization system", description: "Maintains safe cabin pressure at cruising altitude. Supplied by Boeing and specialist environmental-control manufacturers." },
            { name: "Flight-management computers", description: "Calculate routes, navigation information and aircraft-performance data. Major avionics supplied by Honeywell." },
            { name: "Air-data computers", description: "Calculate airspeed, altitude and other flight information. Supplied by Honeywell and other avionics manufacturers." },
            { name: "Inertial reference systems", description: "Provide aircraft attitude, position and movement information. Supplied by Honeywell and other avionics manufacturers." },
            { name: "Fly-by-wire flight-control computers", description: "Interpret pilot inputs and command the aircraft's flight-control surfaces electronically. Developed or supplied by Boeing with major systems from Honeywell and other avionics suppliers." },
            { name: "Autopilot system", description: "Automatically controls the aircraft's flight path when engaged. Major systems supplied by Honeywell and other avionics manufacturers." },
            { name: "Flight displays", description: "Show pilots information such as altitude, speed, heading, navigation and aircraft systems. Supplied by Boeing and avionics manufacturers including Honeywell and Collins." },
            { name: "Communication radios", description: "Allow pilots to communicate with ATC and other aircraft. Supplied by Collins Aerospace, Honeywell and other avionics manufacturers." },
            { name: "Navigation equipment", description: "Determines aircraft position and assists with navigation. Supplied by Honeywell, Collins Aerospace and other manufacturers." },
            { name: "Passenger doors", description: "Provide access to and from the passenger cabin. Manufactured by Boeing and specialist aerospace suppliers." },
            { name: "Cargo doors", description: "Provide access to the aircraft's cargo compartments. Manufactured by Boeing and suppliers." },
            { name: "Cargo handling system", description: "Loads, moves and secures cargo containers and pallets. Supplied by Boeing and specialist cargo-system manufacturers." },
            { name: "Cabin windows", description: "Provide outside visibility while maintaining cabin pressure. Manufactured by specialist aerospace window suppliers." },
            { name: "Passenger seats", description: "Provide passenger seating and restraint systems. Supplied by manufacturers such as Recaro, Safran Seats and Collins Aerospace, depending on airline." },
            { name: "Overhead bins", description: "Store passengers' carry-on luggage. Manufactured or supplied by Boeing and cabin-interior suppliers." },
            { name: "Galleys", description: "Provide facilities for preparing and storing food and drinks. Supplied by Boeing and specialist cabin suppliers." },
            { name: "Lavatories", description: "Provide toilet and washing facilities. Supplied by Boeing and specialist cabin-interior manufacturers." },
        ]
    },
    b787: {
        name: "Boeing 787",
        image: "imgs/planes/b787.webp",
        parts: [
            { name: "Fuselage", description: "Main body of the aircraft, carrying passengers, cargo, fuel-system components and other equipment. Manufactured mainly from composite sections by Boeing, with major sections supplied by Kawasaki Heavy Industries, Fuji Heavy Industries and other partners." },
            { name: "Composite fuselage sections", description: "Lightweight pressure sections forming the main cabin structure. Manufactured by Boeing, Kawasaki Heavy Industries and other Boeing partners." },
            { name: "Wings", description: "Generate lift, contain fuel and support the engines. Manufactured by Mitsubishi Heavy Industries." },
            { name: "Wing center section", description: "Connects the wings to the fuselage and transfers aerodynamic loads. Manufactured by Fuji Heavy Industries." },
            { name: "Horizontal stabilizer", description: "Provides pitch stability and supports the elevators. Manufactured by Alenia Aeronautica and Boeing partners." },
            { name: "Vertical stabilizer / fin", description: "Provides directional stability and supports the rudder. Manufactured by Boeing and major aerospace partners." },
            { name: "Rudder", description: "Controls yaw, moving the aircraft's nose left or right. Manufactured by Boeing and suppliers." },
            { name: "Elevators", description: "Control pitch, moving the aircraft's nose up or down. Manufactured by Boeing and suppliers." },
            { name: "Ailerons", description: "Control the aircraft's roll. Manufactured by Boeing and suppliers." },
            { name: "Flaps", description: "Increase wing lift during takeoff and landing. Manufactured by Boeing and aerospace partners." },
            { name: "Leading-edge slats", description: "Increase lift at low speeds. Manufactured by Boeing and suppliers." },
            { name: "Spoilers", description: "Reduce lift and help control roll and slow the aircraft after landing. Manufactured by Boeing and suppliers." },
            { name: "GEnx engines", description: "Produce thrust for many 787s. Manufactured by GE Aerospace." },
            { name: "Trent 1000 engines", description: "Produce thrust for 787s using the Rolls-Royce engine option. Manufactured by Rolls-Royce." },
            { name: "Engine nacelles", description: "Enclose and streamline the engines. Manufactured by Safran Nacelles and other aerospace suppliers." },
            { name: "Engine pylons", description: "Attach the engines to the wings and transfer engine loads into the wing structure. Manufactured by Boeing and suppliers." },
            { name: "Landing gear", description: "Supports the aircraft on the ground and absorbs landing forces. Manufactured primarily by Safran Landing Systems." },
            { name: "Wheels and brakes", description: "Allow taxiing and provide braking during landing. Supplied by Safran Landing Systems and other specialist manufacturers." },
            { name: "Fuel system", description: "Stores fuel in the wings and center tank and delivers it to the engines. Supplied by Boeing and specialist fuel-system manufacturers." },
            { name: "Hydraulic system", description: "Provides hydraulic power for brakes, landing gear and other aircraft systems. Supplied by Boeing and aerospace-system manufacturers." },
            { name: "Electrical system", description: "Generates and distributes electrical power throughout the aircraft. Major systems supplied by Collins Aerospace and other Boeing partners." },
            { name: "APU", description: "Provides electrical power and compressed air when the main engines aren't running. Manufactured by Honeywell." },
            { name: "Air-conditioning system", description: "Controls cabin temperature and supplies conditioned air. Major systems supplied by Hamilton Sundstrand/Collins Aerospace and other suppliers." },
            { name: "Pressurization system", description: "Maintains safe cabin pressure at cruising altitude. Supplied by Boeing and environmental-control-system manufacturers." },
            { name: "Flight-management computers", description: "Calculate routes, navigation information and aircraft-performance data. Major avionics supplied by Honeywell." },
            { name: "Air-data computers", description: "Calculate airspeed, altitude and other flight information. Supplied by Honeywell and other avionics manufacturers." },
            { name: "Inertial reference systems", description: "Provide aircraft attitude, position and movement information. Supplied by Honeywell and other avionics manufacturers." },
            { name: "Fly-by-wire computers", description: "Process pilot commands and electronically control the aircraft's flight-control surfaces. Developed by Boeing with major systems supplied by Honeywell and other partners." },
            { name: "Autopilot system", description: "Automatically controls the aircraft's flight path when engaged. Major systems supplied by Honeywell." },
            { name: "Flight displays", description: "Show pilots speed, altitude, heading, navigation and aircraft-system information. Supplied by Boeing and avionics manufacturers including Honeywell and Rockwell Collins." },
            { name: "Communication radios", description: "Allow pilots to communicate with ATC and other aircraft. Supplied by Rockwell Collins/Collins Aerospace and other avionics manufacturers." },
            { name: "Navigation equipment", description: "Determines aircraft position and assists with navigation. Supplied by Honeywell, Collins Aerospace and other manufacturers." },
            { name: "Passenger doors", description: "Provide access to and from the passenger cabin. Manufactured by Boeing and aerospace suppliers." },
            { name: "Cargo doors", description: "Provide access to the aircraft's cargo compartments. Manufactured by Boeing and suppliers." },
            { name: "Cargo handling system", description: "Moves and secures cargo containers and baggage inside the aircraft. Supplied by Boeing and specialist cargo-system manufacturers." },
            { name: "Cabin windows", description: "Provide outside visibility while maintaining cabin pressure. Manufactured by PPG Aerospace and other specialist suppliers." },
            { name: "Passenger seats", description: "Provide passenger seating and restraint systems. Supplied by companies such as Collins Aerospace, Safran Seats and Recaro, depending on airline." },
            { name: "Overhead bins", description: "Store passengers' carry-on luggage. Manufactured or supplied by Boeing and cabin-interior suppliers." },
            { name: "Galleys", description: "Provide facilities for preparing and storing food and drinks. Supplied by Boeing and specialist cabin suppliers." },
            { name: "Lavatories", description: "Provide toilet and washing facilities. Supplied by Boeing and specialist cabin-interior manufacturers." },
            { name: "Cabin lighting", description: "Provides general, reading and emergency lighting inside the cabin. Supplied by Boeing and specialist lighting manufacturers." },
            { name: "Passenger entertainment system", description: "Provides movies, music, information and other entertainment to passengers. Supplied by companies such as Panasonic Avionics and Thales, depending on aircraft configuration." },
        ]
    }
};